{{- if and .Values.cloudConfig (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nico-ccm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nico-ccm.labels" . | nindent 4 }}
type: Opaque
stringData:
  cloud-config: {{ .Values.cloudConfig | quote }}
{{- end }}
