apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvidia-carbide-ccm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-carbide-ccm.labels" . | nindent 4 }}
