apiVersion: v2
name: nico-ccm
description: NICo Cloud Controller Manager for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - nvidia
  - nico
  - cloud-controller-manager
  - ccm
